# Site settings
author: Matt Farmer
title: Farmer & the Dell
header-img: img/laptop-keyboard.jpg
email: mrfarmer777@gmail.com
copyright_name: Matt Farmer
description: > # this means to ignore newlines until "baseurl:"
  Solving complex problems with code written on a very old computer.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: mrfarmer777
github_username:  mrfarmer777
linkedin_username: matthew-r-farmer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
