# Site settings
title: Farmer and the Dell
header-img: img/home-bg.png
email: mrfarmer777@gmail.com
copyright_name: mrfarmer777
description: > # this means to ignore newlines until "baseurl:"
  Learning to build with code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: mrfarmer777
github_username:  mrfarmer777
learn_profile: mrfarmer777
email_username: mrfarmer777@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
